const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={kind:'majeur',club:'',type:'',nom:'',prenom:'',birth:'',nationalite:'Française',signatureDate:new Date().toLocaleDateString('fr-CA'),sante:{}};
let step=0,signature=null,signatureDirty=false,previewUrl=null,resultUrl=null;
const titles=['Vos coordonnées','Votre licence','Santé & autorisations','Assurance & encadrement','Signature & téléchargement'];
const adultQuestions=["Un membre de votre famille est-il décédé subitement d’une cause cardiaque ou inexpliquée ?","Avez-vous ressenti une douleur dans la poitrine, des palpitations, un essoufflement inhabituel ou un malaise ?","Avez-vous eu un épisode de respiration sifflante (asthme) ?","Avez-vous eu une perte de connaissance ?","Si vous avez arrêté le sport pendant 30 jours ou plus pour des raisons de santé, avez-vous repris sans l’accord d’un médecin ?","Avez-vous débuté un traitement médical de longue durée (hors contraception et désensibilisation aux allergies) ?","Ressentez-vous une douleur, un manque de force ou une raideur suite à un problème osseux, articulaire ou musculaire (fracture, entorse, luxation, déchirure, tendinite, etc.) survenu durant les 12 derniers mois ?","Votre pratique sportive est-elle interrompue pour des raisons de santé ?","Pensez-vous avoir besoin d’un avis médical pour poursuivre votre pratique sportive ?"];
const minorQuestions=["Es-tu allé(e) à l’hôpital pendant toute une journée ou plusieurs jours ?","As-tu été opéré(e) ?","As-tu beaucoup plus grandi que les autres années ?","As-tu beaucoup maigri ou grossi ?","As-tu eu la tête qui tourne pendant un effort ?","As-tu perdu connaissance ou es-tu tombé sans te souvenir de ce qui s’était passé ?","As-tu reçu un ou plusieurs chocs violents qui t’ont obligé à interrompre un moment une séance de sport ?","As-tu eu beaucoup de mal à respirer pendant un effort par rapport à d’habitude ?","As-tu eu beaucoup de mal à respirer après un effort ?","As-tu eu mal dans la poitrine ou des palpitations (le cœur qui bat très vite) ?","As-tu commencé à prendre un nouveau médicament tous les jours et pour longtemps ?","As-tu arrêté le sport à cause d’un problème de santé pendant un mois ou plus ?","Te sens-tu très fatigué(e) ?","As-tu du mal à t’endormir ou te réveilles-tu souvent dans la nuit ?","Sens-tu que tu as moins faim ? Que tu manges moins ?","Te sens-tu triste ou inquiet ?","Pleures-tu souvent ?","Ressens-tu une douleur ou un manque de force à cause d’une blessure que tu t’es faite cette année ?","Penses-tu quelquefois à arrêter de faire du sport ou à changer de sport ?","Penses-tu avoir besoin de voir ton médecin pour continuer le sport ?","Souhaites-tu signaler quelque chose concernant ta santé ?","Quelqu’un dans votre famille proche a-t-il eu une maladie grave du cœur ou du cerveau, ou est-il décédé subitement avant l’âge de 50 ans ?","Êtes-vous inquiet pour son poids ? Trouvez-vous qu’il se nourrit trop ou pas assez ?","Avez-vous manqué l’examen de santé prévu à l’âge de votre enfant chez le médecin ? (à 2 ans, 3 ans, 4 ans, 5 ans, puis entre 8 et 9 ans, entre 11 et 13 ans et entre 15 et 16 ans)"];
const disciplines=['Natation','Natation artistique','Plongeon','Water-polo','Eau libre','Nagez Forme Santé','Nagez Forme Bien-être'];
function field(id,label,type='text',required=false,full=false,max=100){return `<label class="field ${full?'full':''}">${label}${required?' *':''}<input name="${id}" type="${type}" value="${esc(state[id])}" ${required?'required':''} maxlength="${max}" ${id==='email'?'autocomplete="email"':id==='nom'?'autocomplete="family-name"':id==='prenom'?'autocomplete="given-name"':''}></label>`;}
function select(id,label,options,required=false){return `<label class="field">${label}${required?' *':''}<select name="${id}" ${required?'required':''}><option value="">Choisir…</option>${options.map(o=>{let [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${state[id]===v?'selected':''}>${esc(l)}</option>`}).join('')}</select></label>`;}
function check(id,label){return `<label class="choice"><input type="checkbox" name="${id}" ${state[id]?'checked':''}><span>${label}</span></label>`;}
function radios(id,options){return options.map(([v,label])=>`<label class="choice"><input type="radio" name="${id}" value="${esc(v)}" ${state[id]===v?'checked':''}><span>${label}</span></label>`).join('');}
function allNo(){const q=state.kind==='majeur'?adultQuestions:minorQuestions;return q.every((_,i)=>state.sante[i]==='non');}
function healthNotice(){return Object.values(state.sante).includes('oui')?'<div class="notice warn">Vous avez répondu OUI à au moins une question. Selon le formulaire fourni, un certificat médical de non contre-indication de moins de six mois est demandé. L’attestation de réponses négatives sera laissée vide.</div>':allNo()?'<div class="notice">Toutes les réponses sont NON. Vous pourrez confirmer l’attestation sur l’honneur ci-dessous.</div>':'<div class="notice">Répondez à chaque question. L’attestation sur l’honneur ne sera complétée que si toutes les réponses sont NON et si vous la confirmez.</div>';}
function render(){
 $('#steps').innerHTML=titles.map((t,i)=>`<button type="button" data-step="${i}" aria-label="Étape ${i+1} : ${esc(t)}" class="${i===step?'active':i<step?'done':''}" ${i===step?'aria-current="step"':''}><span>${i<step?'✓':i+1}</span>${t}</button>`).join('');
 $('#counter').textContent=`ÉTAPE ${step+1} SUR 5`;$('#progress').style.width=`${(step+1)*20}%`;$('#prev').style.visibility=step?'visible':'hidden';$('#next').style.display=step===4?'none':'';$('#status').textContent='';
 const minor=state.kind==='mineur';let html='';
 if(step===0)html=`<h2>Commençons par vous.</h2><p class="intro">Les informations de la personne qui demande sa licence. Les champs marqués * sont nécessaires.</p><div class="seg">${[['majeur','Majeur','18 ans et plus'],['mineur','Mineur','À remplir avec un parent']].map(([v,t,d])=>`<label><input type="radio" name="kind" value="${v}" ${state.kind===v?'checked':''}><span><strong>${t}</strong><small>${d}</small></span></label>`).join('')}</div><div class="grid">${field('nom','Nom','text',true)}${field('prenom','Prénom','text',true)}${field('birth','Date de naissance','date',true)}${select('sexe','Sexe (tel que prévu sur le PDF)',[['F','Féminin'],['M','Masculin']],true)}${field('nationalite','Nationalité','text',true)}${field('email','E-mail personnel','email',true)}${field('adresse','Adresse','text',true,true,130)}${field('cp','Code postal','text',true,false,12)}${field('ville','Ville','text',true)}${field('tel','Téléphone principal','tel',true,false,24)}${field('tel2','Deuxième téléphone (facultatif)','tel',false,false,24)}</div>${check('handisport','Je suis athlète handisport')}${minor?`<h3>Personne exerçant l’autorité parentale</h3><div class="grid">${field('parent','Nom et prénom du parent / représentant légal','text',true,true)}</div>`:''}<h3>Informations de la FFN</h3><p class="intro">Souhaitez-vous recevoir les e-mails d’information de la FFN, de la Ligue et du Comité, ainsi que les offres de la FFN et de ses partenaires ?</p>${radios('marketing',[['oui','Oui'],['non','Non']])}`;
 if(step===1)html=`<h2>Choisissez votre licence.</h2><p class="intro">En cas de doute, demandez au club quelle licence correspond à votre groupe.</p><div class="grid">${field('club','Nom de votre club','text',true,true)}${select('type','Type de demande',[['nouvelle','Nouvelle licence'],['renouvellement','Renouvellement'],['transfert','Transfert']],true)}${field('iuf','Identifiant unique fédéral (si connu)','text',false,false,30)}${state.type==='transfert'?field('ancienClub','Nom du club précédent','text',true,true):''}</div><h3>Catégorie de licence</h3>${radios('categorie',[['loisir','Natation pour tous'],['competition','Compétition'],['encadrement','Encadrement'],['eauPromotion','Eau libre promotionnelle'],...(minor?[['apprentissage','J’apprends à nager / Aisance aquatique']]:[])])}${['loisir','competition','encadrement'].includes(state.categorie)?`<div class="grid">${select('discipline','Discipline',state.categorie==='competition'?disciplines.slice(0,5):disciplines,true)}${state.categorie==='encadrement'?select('fonction','Fonction',[['entraineur','Entraîneur'],['officiel','Officiel'],['president','Président'],['secretaire','Secrétaire général'],['tresorier','Trésorier'],['dirigeant','Autre dirigeant'],['benevole','Bénévole']],true):''}</div>`:''}${!minor?check('eauFroide','Je pratique l’eau froide / glacée'):''}<div class="notice">Le formulaire fourni indique qu’une personne pouvant intervenir auprès de mineurs doit aussi renseigner le contrôle d’honorabilité. Cette annexe est accessible à l’étape 4.</div>`;
 if(step===2){const qs=minor?minorQuestions:adultQuestions;html=`<h2>Santé et autorisations.</h2><p class="intro">${minor?'Le questionnaire se remplit ensemble, parent et enfant. Les trois dernières questions sont destinées aux parents.':'Répondez personnellement au questionnaire figurant dans votre formulaire.'}</p><p class="small">Les questions ci-dessous reprennent le document fourni. <a href="${state.kind}.pdf" target="_blank" rel="noopener">Consulter le formulaire original</a>.</p>${minor?`<div class="grid">${field('age','Âge de l’enfant','number',false,false,2)}</div>`:''}${qs.map((q,i)=>`<div class="question">${i===0?'<strong>Durant les 12 derniers mois / depuis l’année dernière</strong><br>':minor&&i===12?'<strong>Depuis un certain temps (plus de 2 semaines)</strong><br>':minor&&i===18||!minor&&i===6?'<strong>Aujourd’hui</strong><br>':minor&&i===21?'<strong>Questions à faire remplir par les parents</strong><br>':''}${i+1}. ${esc(q)}<div class="answers">${['oui','non'].map(v=>`<label><input type="radio" name="q${i}" value="${v}" ${state.sante[i]===v?'checked':''}> ${v==='oui'?'Oui':'Non'}</label>`).join('')}</div></div>`).join('')}<div id="healthnotice">${healthNotice()}</div>${check('attest',`J’atteste sur l’honneur avoir répondu ${minor?'conjointement avec le mineur concerné, ':''}NON à toutes les questions du questionnaire de santé.`)}${minor?`<h3>Autorisation parentale</h3>${check('prelevement','J’autorise tout prélèvement nécessitant une technique invasive (prise de sang, prélèvement de phanères) lors d’un contrôle antidopage du mineur.')}${check('informationDopage','Je reconnais être informé(e) que l’absence d’autorisation parentale est constitutive d’un refus de contrôle et est susceptible d’entraîner des sanctions disciplinaires.')}`:''}<div class="notice">Chaque réponse Oui ou Non sera cochée dans le questionnaire de santé du PDF téléchargé. L’attestation de réponses négatives est complétée uniquement si toutes les réponses sont NON et si vous la confirmez.</div>`;}
 if(step===3)html=`<h2>Vos choix et garanties.</h2><p class="intro">Consultez la notice d’assurance intégrée au formulaire avant de choisir.</p><a href="${state.kind}.pdf#page=2" target="_blank" rel="noopener">Lire la notice et les garanties FFN / MAIF ↗</a><h3>Garantie de base « Individuelle accident »</h3>${radios('assurance',[['oui','Je souhaite bénéficier de la garantie Individuelle Accident et Assistance Rapatriement comprise dans la licence.'],['non','Je renonce à ces garanties et à toute couverture en cas d’accident corporel (réduction indiquée sur le formulaire : 0,15 €).']])}<h3>Garantie complémentaire</h3>${radios('complement',[['oui','Je souhaite souscrire une option complémentaire.'],['non','Je ne souhaite pas souscrire d’option complémentaire.']])}${state.complement==='oui'?'<div class="notice warn">Le bordereau MAIF page 3 sera prérempli. La souscription nécessite aussi son envoi à l’assureur avec le règlement, selon les instructions du document.</div>':''}${check('luAssurance','Je reconnais avoir reçu ou consulté les informations sur les garanties et la possibilité de souscrire des garanties complémentaires.')}${check('honorabilite','Je dois compléter le contrôle d’honorabilité (encadrement ou intervention auprès de mineurs).')}${state.honorabilite?`<h3>Contrôle d’honorabilité</h3>${check('accepteControle','J’ai compris l’objet du contrôle décrit en page 4 et j’accepte ce contrôle.')}<div class="grid">${field('nomNaissance','Nom de naissance','text',true)}${field('prenomNaissance','Prénom de naissance','text',true)}${field('nomUsage','Nom d’usage (si différent)')}${field('prenomUsage','Prénom d’usage (si différent)')}${select('lieuNaissance','Lieu de naissance',[['france','En France'],['etranger','À l’étranger']],true)}${state.lieuNaissance==='france'?field('departement','Département de naissance','text',true,false,3):field('pays','Pays de naissance','text',true)}${field('commune','Commune de naissance','text',true)}${field('arrondissement','Arrondissement (si nécessaire)','text',false,false,4)}${field('nomMere','Nom de la mère (facultatif)')}${field('prenomMere','Prénom de la mère (facultatif)')}${field('nomPere','Nom du père (facultatif)')}${field('prenomPere','Prénom du père (facultatif)')}</div>`:''}`;
 if(step===4)html=`<h2>Votre dossier est presque prêt.</h2><p class="intro">Vérifiez vos informations, puis téléchargez votre formulaire complété.</p><div class="review"><div><small>LICENCIÉ</small><strong>${esc(state.prenom)} ${esc(state.nom)}</strong></div><div><small>FORMULAIRE</small><strong>${minor?'Mineur':'Majeur'} · 2026–2027</strong></div><div><small>CLUB</small>${esc(state.club)}</div><div><small>LICENCE</small>${esc({loisir:'Natation pour tous',competition:'Compétition',encadrement:'Encadrement',eauPromotion:'Eau libre promotionnelle',apprentissage:'J’apprends à nager'}[state.categorie])}${state.discipline?' · '+esc(state.discipline):''}</div></div><div class="grid">${field('signatureVille','Fait à (ville)','text',true)}${field('signatureDate','Date','date',true)}</div><h3>Signature ${minor?'du parent / représentant légal':'du licencié (ou de son représentant légal)'}</h3><p class="intro">Dessinez votre signature avec la souris ou votre doigt. Vous pouvez aussi signer le PDF après impression. La zone de signature du club reste réservée au club.</p><canvas id="signature" width="1000" height="310" aria-label="Zone pour dessiner une signature"></canvas><button type="button" class="secondary" id="clearSignature">Effacer la signature</button>${check('signatureConsent','Je souhaite apposer cette signature dessinée sur les emplacements du dossier qui me concernent.')}<div class="notice">Après téléchargement : vérifiez le PDF, signez-le si nécessaire, puis ajoutez-le manuellement à Swim Community. Aucun envoi automatique n’est effectué.</div><p class="mobile-help">Sur téléphone, vous pouvez signer avec votre doigt. Une fois le PDF prêt, ouvrez-le pour l’enregistrer dans vos fichiers. Sur iPhone, utilisez le bouton de partage du lecteur PDF, puis « Enregistrer dans Fichiers ».</p><p id="errors" class="error" role="alert"></p><button type="button" class="download" id="download">↓ Télécharger mon PDF complété</button><button type="button" class="secondary" id="preview" style="width:100%;margin-top:10px">Voir le PDF avant téléchargement</button>`;
 $('#content').innerHTML=html+(step<4?'<p id="errors" class="error" role="alert"></p>':'');
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{save();const target=Number(b.dataset.step);if(target>step&&!validate())return;step=target;render();});
 if(step===4){initSignature();$('#download').onclick=()=>output(false);$('#preview').onclick=()=>output(true);$('#clearSignature').onclick=()=>{signature=null;signatureDirty=false;$('#signature').getContext('2d').clearRect(0,0,$('#signature').width,$('#signature').height);};}
}
function save(){document.querySelectorAll('#content input,#content select').forEach(e=>{if(e.name.startsWith('q')&&/^q\d+$/.test(e.name)){if(e.checked)state.sante[Number(e.name.slice(1))]=e.value;}else if(e.type==='radio'){if(e.checked)state[e.name]=e.value;}else state[e.name]=e.type==='checkbox'?e.checked:e.value;});if(signatureDirty&&$('#signature'))signature=$('#signature').toDataURL('image/png');}
function validDateAge(){if(!state.birth)return null;const b=new Date(state.birth+'T12:00:00');let a=new Date().getFullYear()-b.getFullYear();const n=new Date();if(n.getMonth()<b.getMonth()||n.getMonth()===b.getMonth()&&n.getDate()<b.getDate())a--;return a;}
function validate(){save();let error='';for(const e of document.querySelectorAll('#content [required]'))if(!e.checkValidity()){error='Veuillez compléter : '+e.closest('label').firstChild.textContent;e.focus();break;}
 if(!error&&step===0){const a=validDateAge();if(a===null||a<0||a>120)error='Veuillez vérifier la date de naissance.';else if(state.kind==='mineur'&&a>=18||state.kind==='majeur'&&a<18)error='La date de naissance ne correspond pas au formulaire choisi. Vérifiez le choix majeur / mineur.';else if(!state.marketing)error='Veuillez choisir Oui ou Non pour les e-mails de la FFN.';}
 if(!error&&step===1&&!state.categorie)error='Veuillez choisir une catégorie de licence.'; if(!error&&step===1&&state.categorie==='encadrement'&&state.fonction==='officiel'&&disciplines.indexOf(state.discipline)>4)error='Le formulaire ne prévoit pas de fonction Officiel pour cette discipline. Vérifiez votre choix avec le club.';
 if(!error&&step===2){const qs=state.kind==='majeur'?adultQuestions:minorQuestions;if(!qs.every((_,i)=>state.sante[i]))error='Veuillez répondre à toutes les questions du questionnaire de santé.';else if(state.attest&&!allNo())error='L’attestation de réponses négatives ne peut pas être cochée avec une réponse OUI.';else if(allNo()&&!state.attest)error='Veuillez confirmer l’attestation de réponses négatives.';}
 if(!error&&step===3){if(!state.assurance||!state.complement)error='Veuillez choisir les garanties de base et complémentaires.';else if(!state.luAssurance)error='Veuillez confirmer la consultation des informations d’assurance.';else if(state.categorie==='encadrement'&&!state.honorabilite)error='La licence Encadrement nécessite le contrôle d’honorabilité.';else if(state.honorabilite&&!state.accepteControle)error='Veuillez confirmer que vous acceptez le contrôle d’honorabilité.';}
 if(!error&&step===4&&state.signatureConsent&&!signature)error='Dessinez votre signature ou décochez l’ajout de signature pour signer après impression.';
 $('#errors').textContent=error;return !error;
}
$('#form').addEventListener('input',e=>{const old=state.kind;save();if(e.target.name==='kind'){if(old!==state.kind){state.sante={};state.attest=false;}render();}else if(/^q\d+$/.test(e.target.name)){if(!allNo()){state.attest=false;const a=document.querySelector('[name=attest]');if(a)a.checked=false;}$('#healthnotice').innerHTML=healthNotice();}});
$('#form').addEventListener('change',e=>{save();if(['type','categorie','honorabilite','lieuNaissance','complement'].includes(e.target.name))render();});
$('#form').onsubmit=e=>{e.preventDefault();if(validate()){step=Math.min(4,step+1);render();window.scrollTo({top:0,behavior:'smooth'});}};$('#prev').onclick=()=>{save();step--;render();};
function initSignature(){signatureDirty=false;const c=$('#signature'),r=c.getBoundingClientRect(),ratio=Math.min(window.devicePixelRatio||1,2);c.width=Math.round(r.width*ratio);c.height=Math.round(r.height*ratio);const ctx=c.getContext('2d');ctx.lineWidth=2*ratio;ctx.lineCap='round';ctx.strokeStyle='#123c50';if(signature){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.width,c.height);im.src=signature;}let drawing=false;const point=e=>{const r=c.getBoundingClientRect();return [(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height];};c.onpointerdown=e=>{drawing=true;signatureDirty=true;c.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e));};c.onpointermove=e=>{if(drawing){ctx.lineTo(...point(e));ctx.stroke();}};c.onpointerup=c.onpointercancel=()=>{drawing=false;signature=c.toDataURL('image/png');};}
function pdfValues(){const m=state.kind==='mineur',v={};const text=(n,val)=>{if(val)v[n]=String(val);},cb=(n,on)=>{if(on)v['Check Box'+n]=true;};
 const healthPairs=m?[[80,82],[83,84],[85,86],[87,88],[89,90],[91,92],[93,94],[95,96],[97,98],[99,100],[101,102],[103,104],[105,106],[107,108],[109,110],[111,112],[113,114],[115,116],[117,118],[119,120],[121,122],[123,124],[125,126],[127,128]]:[[85,86],[87,88],[97,90],[91,92],[93,94],[95,96],[98,99],[100,101],[102,103]];
 healthPairs.forEach(([yes,no],i)=>{cb(yes,state.sante[i]==='oui');cb(no,state.sante[i]==='non');});
 if(m){cb(78,state.sexe==='F');cb(79,state.sexe==='M');text('Text81',state.age||validDateAge());}
 cb(1,state.type==='nouvelle');cb(2,state.type==='renouvellement');cb(3,state.type==='transfert');text('Text4',state.ancienClub);text('Text5',state.iuf);text('Text6',state.nom);text('Text7',state.prenom);text('Text8',state.nationalite);text(m?'Dropdown135':'Dropdown19',m&&state.sexe==='M'?'H':state.sexe);
 const [y,mo,d]=state.birth.split('-');[d,mo,y].forEach((val,i)=>text('Text'+((m?136:16)+i),val));text('Text9',state.adresse);text('Text10',state.cp);text('Text11',state.ville);const at=state.email.lastIndexOf('@');text(m?'Text13':'Text12',state.email.slice(0,at));text(m?'Text14':'Text13',state.email.slice(at+1));text(m?'Text15':'Text14',state.tel);text(m?'Text16':'Text15',state.tel2);cb(m?12:20,state.handisport);cb(m?33:21,state.marketing==='oui');cb(m?34:22,state.marketing==='non');
 const idx=disciplines.indexOf(state.discipline);if(state.categorie==='loisir')cb((m?17:24)+idx,true);if(state.categorie==='competition')cb((m?24:32)+idx,true);cb(m?29:31,state.categorie==='eauPromotion');if(m)cb(30,state.categorie==='apprentissage');else cb(23,state.eauFroide);
 if(state.categorie==='encadrement'){if(state.fonction==='entraineur')cb((m?[32,35,36,37,38,39,40]:[38,40,41,42,43,44,45])[idx],true);else if(state.fonction==='officiel'){if(idx<5)cb((m?41:46)+idx,true);}else{const fi=['president','secretaire','tresorier','dirigeant','benevole'].indexOf(state.fonction);if(fi>=0)cb((m?46:51)+fi,true);}}
 const negative=allNo()&&state.attest;cb(m?51:39,negative);if(m){cb(52,state.prelevement);cb(53,state.informationDopage);}cb(m?54:56,state.assurance==='oui');cb(m?55:57,state.assurance==='non');cb(m?56:58,state.complement==='oui');cb(m?57:59,state.complement==='non');const date=state.signatureDate.split('-').reverse().join('/');text(m?'Text58':'Text60',state.signatureVille);text(m?'Text59':'Text61',date);
 if(state.complement==='oui'){text(m?'Je soussignée nom prénom':'Text62',state.prenom+' '+state.nom);text(m?'Date de naissance':'Text63',[d,mo,y].join('/'));text(m?'Adresse':'Text64',state.adresse+' '+state.cp+' '+state.ville);text(m?'Text62':'Text65',state.signatureVille);text(m?'Text63':'Text66',date);}
 if(state.honorabilite){cb(m?31:37,state.accepteControle);cb(m?64:67,state.accepteControle);text(m?'Nom de naissance':'Text70',state.nomNaissance);text(m?'Text68':'Text71',state.prenomNaissance);text(m?'Nom dusage':'Text72',state.nomUsage);text(m?'Text69':'Text73',state.prenomUsage);cb(m?65:68,state.lieuNaissance==='france');cb(m?66:69,state.lieuNaissance==='etranger');text(m?'Text67':'Text74',state.departement);if(state.lieuNaissance==='france'){text(m?'Text70':'Text75',state.commune);if(m)text('Text71',state.arrondissement);}else{text(m?'Text73':'Text77',state.pays);text(m?'Text72':'Text79',state.commune);}text(m?'Text74':'Text78',state.nomMere);text(m?'Text75':'Text80',state.prenomMere);text(m?'Nom du père':'Text81',state.nomPere);text(m?'Prénom du père':'Text82',state.prenomPere);text(m?'Text76':'Text83',state.signatureVille);text(m?'Text77':'Text84',date);}
 if(negative){text(m?'Text129':'Text104',m?state.parent:state.prenom+' '+state.nom);text(m?'Nom du Club':'Text105',state.club);text(m?'Demeurant':'Text106',state.adresse);text(m?'Text130':'Text107',state.cp+' '+state.ville);text(m?'Text132':'Text109',state.signatureVille);text(m?'Text134':'Text110',date);}
 return v;
}
async function makePdf(){const {PDFDocument,StandardFonts,rgb}=PDFLib;const res=await fetch(state.kind+'.pdf');if(!res.ok)throw Error('Le formulaire original est indisponible.');const doc=await PDFDocument.load(await res.arrayBuffer());const form=doc.getForm(),font=await doc.embedFont(StandardFonts.Helvetica);const values=pdfValues();for(const [name,val]of Object.entries(values)){const f=form.getField(name);if(typeof val==='boolean')f.check();else if(f instanceof PDFLib.PDFDropdown)f.select(val);else {let size=10;const widget=f.acroField.getWidgets()[0],r=widget.getRectangle();while(size>5&&font.widthOfTextAtSize(val,size)>r.width-4)size-=.25;if(font.widthOfTextAtSize(val,size)>r.width-4)throw Error('Le texte du champ '+name+' est trop long pour le PDF. Raccourcissez-le.');f.setText(val);f.setFontSize(size);}}
 form.updateFieldAppearances(font);
 if(state.honorabilite&&state.kind==='majeur'&&state.arrondissement){const f=form.getField('Check Box76');const r=f.acroField.getWidgets()[0].getRectangle();form.removeField(f);doc.getPages()[3].drawText(state.arrondissement,{x:r.x+2,y:r.y+6,size:10,font,color:rgb(.05,.15,.2)});}
 if(signature&&state.signatureConsent){const im=await doc.embedPng(signature);const put=(page,x,y,w,h)=>{const fit=im.scaleToFit(w,h);doc.getPages()[page].drawImage(im,{x:x+(w-fit.width)/2,y:y+(h-fit.height)/2,width:fit.width,height:fit.height});};put(0,385,27,175,57);if(state.honorabilite)put(3,220,145,320,65);if(allNo()&&state.attest)put(state.kind==='mineur'?6:5,395,35,165,40);if(state.complement==='oui')put(2,420,15,135,35);}
 doc.setTitle('Licence FFN 2026–2027 — '+state.prenom+' '+state.nom);doc.setSubject('Demande de licence '+state.kind);return await doc.save();}
async function output(preview){save();for(let i=0;i<5;i++){step=i;render();if(!validate())return;}const buttons=[$('#download'),$('#preview')];buttons.forEach(b=>b.disabled=true);$('#status').textContent='Préparation de votre PDF…';try{const bytes=await makePdf();const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));if(preview){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=url;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();}else{const a=document.createElement('a');a.href=url;a.download=`Licence-FFN-${state.kind}-${state.nom.replace(/[^a-zA-ZÀ-ÿ0-9-]/g,'_')}-2026-2027.pdf`;document.body.append(a);a.click();a.remove();if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=url;}$('#status').textContent='Votre PDF est prêt. Vérifiez-le et ajoutez-le à Swim Community. Vous pourrez le modifier dans cette application tant que la page reste ouverte.';const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.textContent='Ouvrir ou enregistrer mon PDF';$('#status').append(document.createElement('br'),link);}catch(e){$('#status').textContent='Impossible de générer le PDF : '+e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_licence_step',title:'Afficher une étape de licence',description:'Affiche une étape du formulaire existant. Ne télécharge et ne transmet aucune donnée.',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:1,maximum:5}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input.step)||input.step<1||input.step>5)throw Error('Étape invalide');save();if(input.step-1>step&&!validate())throw Error('Complétez d’abord l’étape courante');step=input.step-1;render();return{step:step+1,title:titles[step]};}})).catch(()=>{});}catch{}}



